[Writable]
  LogLevel = 'INFO'
  [Writable.Device]
    [Writable.Device.Discovery]
      Enabled = true
  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.DB]
    path = "redisdb"
      [Writable.InsecureSecrets.DB.Secrets]
      username = ""
      password = ""
    [Writable.InsecureSecrets.MQTT]
    path = "credentials"
      [Writable.InsecureSecrets.MQTT.Secrets]
      username = ""
      password = ""
  [Writable.Telemetry]
  Interval = "30s"
  PublishTopicPrefix  = "edgex/telemetry" # /<service-name>/<metric-name> will be added to this Publish Topic prefix
    [Writable.Telemetry.Metrics] # All service's metric names must be present in this list.
    # Device SDK provided Service Metrics
    EventsSent = false
    ReadingsSent = false
    # Common Security Service Metrics
    SecuritySecretsRequested = false
    SecuritySecretsStored = false
    SecurityConsulTokensRequested = false
    SecurityConsulTokenDuration = false

[Service]
  ServerBindAddr = "" # blank value defaults to hostname
  Port = 59980
  StartupMsg = "BACnet device service started"
  MaxRequestSize = 0
  RequestTimeout = "5s"
  HealthCheckInterval = "10s"

[Registry]
  Host = "localhost"
  Port = 8500
  Type = "consul"

[Clients]
  [Clients.core-data]
    Host = "localhost"
    Port = 59880

  [Clients.core-metadata]
    Host = "localhost"
    Port = 59881

[Device]
  ProfilesDir = "./res/ip/profiles"
  DevicesDir = "./res/ip/devices"

[Driver]
#  BBMD_ADDRESS = "10.100.22.243"
#  BBMD_PORT = "47809"

[MessageQueue]
  Protocol = "redis"
  Host = "localhost"
  Port = 6379
  Type = "redis"
  AuthMode = "usernamepassword"  # required for redis messagebus (secure or insecure)
  SecretName = "redisdb"
  PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  [MessageQueue.Optional]
    ClientId = "device-bacnet"
    Qos = 0 # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive = 10 # Seconds (must be 2 or greater)
    Retained = false
    SkipCertVerify = false
  [MessageQueue.Topics]
    CommandRequestTopic = "edgex/device/command/request/device-bacnet/#"   # subscribing for inbound command requests
    CommandResponseTopicPrefix = "edgex/device/command/response"   # publishing outbound command responses; <device-service>/<device-name>/<command-name>/<method> will be added to this publish topic prefix

[SecretStore]
  Type = "vault"
  Host = "localhost"
  Port = 8200
  Path = "device-bacnet/"
  Protocol = "http"
  RootCaCertPath = ""
  ServerName = ""
  # Uncomment to seed service secrets file
  # SecretsFile = "/tmp/edgex/secrets/device-bacnet/secrets.json"
  DisableScrubSecretsFile = false
  TokenFile = "/tmp/edgex/secrets/device-bacnet/secrets-token.json"
  [SecretStore.Authentication]
    AuthType = "X-Vault-Token"
