[Service]
  ServerBindAddr = '0.0.0.0'
  Port = 49981
  ConnectRetries = 3
  HealthCheck = ''
  Labels = [ 'BACnet' ]
  OpenMsg = 'BACnet started'
  ReadMaxLimit = 256
  Timeout = 5000
  CheckInterval = '10s'

[Clients]
  [Clients.Data]
    Host = 'edgex-core-data'
    Port = 48080

  [Clients.Metadata]
    Host = 'edgex-core-metadata'
    Port = 48081

[Device]
  DataTransform = true
  Discovery = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = '/profiles'
  SendReadingsOnChanged = true

[Driver]
  DefaultDevicePath = '/dev/ttyUSB0'
